setup debug

diff --git a/.github/workflows/nm-benchmark.yml b/.github/workflows/nm-benchmark.yml
--- a/.github/workflows/nm-benchmark.yml
+++ b/.github/workflows/nm-benchmark.yml
@@ -27,10 +27,6 @@ on:
         description: "python version, e.g. 3.10.12"
         type: string
         required: true
-      trigger_type:
-        description: "A string describing the caller of this workflow"
-        type: string
-        required: true
 
   # makes workflow manually callable
   workflow_dispatch:
@@ -59,10 +55,6 @@ on:
         description: "python version, e.g. 3.10.12"
         type: string
         required: true
-      trigger_type:
-        description: "A string describing the caller of this workflow"
-        default: "user_dispatch"
-        type: string
 
 jobs:
   BENCHMARK:
@@ -71,54 +63,70 @@ jobs:
     timeout-minutes: ${{ fromJSON(inputs.timeout) }}
 
     steps:
-      - name: checkout repository code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          ref: ${{ inputs.gitref }}
-          submodules: recursive
+      - name: sanity check
+        shell: bash
+        run: |
+          echo "event name is:" ${{ github.event_name }}
+          echo "event type is:" ${{ github.event.action }}
 
-      - name: setenv
-        id: setenv
-        uses: ./.github/actions/nm-set-env/
-        with:
-          hf_token: ${{ secrets.NM_HF_TOKEN }}
-          Gi_per_thread: ${{ inputs.Gi_per_thread }}
+      - name: run iff
+        if: ${{ github.event_name == 'workflow_call' }}
+        run: |
+          echo "This will run only on a workflow_call event"
 
-      - name: set python
-        id: set_python
-        uses: ./.github/actions/nm-set-python/
-        with:
-          python: ${{ inputs.python }}
-          venv: TEST
+      - name: run iff
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        run: |
+          echo "This will run only on a workflow_dispatch event"
 
-      - name: hf cache
-        id: hf_cache
-        uses: ./.github/actions/nm-hf-cache/
-        with:
-          fs_cache: ${{ secrets.HF_FS_CACHE }}
+          #- name: checkout repository code
+          #  uses: actions/checkout@v4
+          #  with:
+          #    fetch-depth: 0
+          #    ref: ${{ inputs.gitref }}
+          #    submodules: recursive
 
-      - name: build
-        id: build
-        uses: ./.github/actions/nm-build-vllm/
-        with:
-          Gi_per_thread: ${{ inputs.Gi_per_thread }}
-          python: ${{ inputs.python }}
-          venv: TEST
-          pypi: ${{ secrets.NM_PRIVATE_PYPI_LOCATION }}
+          #- name: setenv
+          #  id: setenv
+          #  uses: ./.github/actions/nm-set-env/
+          #  with:
+          #    hf_token: ${{ secrets.NM_HF_TOKEN }}
+          #    Gi_per_thread: ${{ inputs.Gi_per_thread }}
 
-      - name: run benchmarks
-        uses: ./.github/actions/nm-benchmark/
-        with:
-          benchmark_config_list_file: ${{ inputs.benchmark_config_list_file }}
-          output_directory: benchmark-results
-          python: ${{ inputs.python }}
-          venv: TEST
+          #- name: set python
+          #  id: set_python
+          #  uses: ./.github/actions/nm-set-python/
+          #  with:
+          #    python: ${{ inputs.python }}
+          #    venv: TEST
 
-      - name: store benchmark result artifacts
-        uses: actions/upload-artifact@v4
-        if: success() || failure()
-        with:
-          name: ${{ github.run_id }}-${{ inputs.label }}
-          path: benchmark-results
-          retention-days: 10
+          #- name: hf cache
+          #  id: hf_cache
+          #  uses: ./.github/actions/nm-hf-cache/
+          #  with:
+          #    fs_cache: ${{ secrets.HF_FS_CACHE }}
+
+          #- name: build
+          #  id: build
+          #  uses: ./.github/actions/nm-build-vllm/
+          #  with:
+          #    Gi_per_thread: ${{ inputs.Gi_per_thread }}
+          #    python: ${{ inputs.python }}
+          #    venv: TEST
+          #    pypi: ${{ secrets.NM_PRIVATE_PYPI_LOCATION }}
+
+          #- name: run benchmarks
+          #  uses: ./.github/actions/nm-benchmark/
+          #  with:
+          #    benchmark_config_list_file: ${{ inputs.benchmark_config_list_file }}
+          #    output_directory: benchmark-results
+          #    python: ${{ inputs.python }}
+          #    venv: TEST
+
+          #- name: store benchmark result artifacts
+          #  uses: actions/upload-artifact@v4
+          #  if: success() || failure()
+          #  with:
+          #    name: ${{ github.run_id }}-${{ inputs.label }}
+          #    path: benchmark-results
+          #    retention-days: 10
