debug - add pause

diff --git a/.github/workflows/nm-benchmark.yml b/.github/workflows/nm-benchmark.yml
--- a/.github/workflows/nm-benchmark.yml
+++ b/.github/workflows/nm-benchmark.yml
@@ -73,18 +73,36 @@ jobs:
           venv: TEST
           pypi: ${{ secrets.NM_PRIVATE_PYPI_LOCATION }}
 
-      - name: run benchmarks
-        uses: ./.github/actions/nm-benchmark/
-        with:
-          benchmark_config_list_file: ${{ inputs.benchmark_config_list_file }}
-          output_directory: benchmark-results
-          python: ${{ inputs.python }}
-          venv: TEST
+      #- name: run benchmarks
+      #  uses: ./.github/actions/nm-benchmark/
+      #  with:
+      #    benchmark_config_list_file: ${{ inputs.benchmark_config_list_file }}
+      #    output_directory: benchmark-results
+      #    python: ${{ inputs.python }}
+      #    venv: TEST
 
-      - name: store benchmark result artifacts
-        uses: actions/upload-artifact@v4
+      #- name: store benchmark result artifacts
+      #  uses: actions/upload-artifact@v4
+      #  if: success() || failure()
+      #  with:
+      #    name: ${{ github.run_id }}-${{ inputs.label }}
+      #    path: benchmark-results
+      #    retention-days: 90
+
+      #######################################################
+      # TODO (Varun) : Remove pause once things are automated
+      - name: announce pause
         if: success() || failure()
-        with:
-          name: ${{ github.run_id }}-${{ inputs.label }}
-          path: benchmark-results
-          retention-days: 90
+        run: |
+          M=${{ inputs.timeout }}
+          R=$((M - 15))
+          S=$((R * 60))
+          echo "pausing for, ${R} minutes"
+
+      - name: pause workflow
+        run: |
+          M=${{ inputs.timeout }}
+          R=$((M - 15))
+          S=$((R * 60))
+          sleep $S
+
